version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-26-alpha
    environment:
      _JAVA_OPTIONS: "-Xmx1400m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2"
    resource_class: large
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Setup emulator
          command: sdkmanager "system-images;android-25;default;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-25;default;armeabi-v7a"
      - run:
          name: Launch emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel on
          background: true
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Local Tests
          command: ./gradlew lint test
      - run:
          name: Wait for device
          command: circle-android wait-for-boot
      - run:
          name: Unlock the device
          command: adb shell input keyevent 82
      - run:
          name: Plug in the device
          command: adb shell svc power stayon true
      - run:
          name: Turn off the WINDOW ANIMATION SCALE
          command: adb shell settings put global window_animation_scale 0
      - run:
          name: Turn off the TRANSITION ANIMATION SCALE
          command: adb shell settings put global transition_animation_scale 0
      - run:
          name: Turn off the ANIMATOR DURATION SCALE
          command: adb shell settings put global animator_duration_scale 0
      - run:
          name: Run Instrumentation Tests
          command: ./gradlew :app:connectedAndroidTest
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results